// Shared brand styling for Dwayne Noe Construction auth emails.
// Email bodies must use a white background (deliverability requirement),
// while accents use the app's sapphire + maple palette.

export const brand = {
  sapphire: '#1e40d6',
  sapphireDeep: '#0a1430',
  maple: '#e89339',
  ink: '#0a1430',
  body: '#3d4860',
  muted: '#8a93a6',
  divider: '#e6e8ef',
  radius: '10px',
  displayFont: "'Oswald', 'Arial Narrow', Arial, sans-serif",
  bodyFont: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif",
}

export const styles = {
  main: {
    backgroundColor: '#ffffff',
    fontFamily: brand.bodyFont,
    margin: 0,
    padding: 0,
  },
  container: {
    padding: '32px 28px',
    maxWidth: '560px',
  },
  brandBar: {
    borderTop: `4px solid ${brand.maple}`,
    paddingTop: '20px',
    marginBottom: '12px',
  },
  brandLabel: {
    fontFamily: brand.displayFont,
    fontSize: '12px',
    letterSpacing: '0.18em',
    color: brand.maple,
    textTransform: 'uppercase' as const,
    margin: '0 0 6px',
    fontWeight: 700 as const,
  },
  h1: {
    fontFamily: brand.displayFont,
    fontSize: '28px',
    fontWeight: 700 as const,
    color: brand.ink,
    letterSpacing: '0.01em',
    textTransform: 'uppercase' as const,
    margin: '0 0 22px',
    lineHeight: '1.15',
  },
  text: {
    fontSize: '15px',
    color: brand.body,
    lineHeight: '1.6',
    margin: '0 0 22px',
  },
  link: { color: brand.sapphire, textDecoration: 'underline' },
  button: {
    backgroundColor: brand.sapphire,
    color: '#ffffff',
    fontSize: '14px',
    fontFamily: brand.displayFont,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
    fontWeight: 700 as const,
    borderRadius: brand.radius,
    padding: '14px 26px',
    textDecoration: 'none',
    display: 'inline-block',
  },
  code: {
    fontFamily: "'Courier New', Courier, monospace",
    fontSize: '28px',
    fontWeight: 700 as const,
    color: brand.ink,
    letterSpacing: '0.25em',
    backgroundColor: '#f4f6fb',
    padding: '16px 20px',
    borderRadius: brand.radius,
    display: 'inline-block',
    margin: '0 0 28px',
  },
  divider: {
    borderTop: `1px solid ${brand.divider}`,
    margin: '32px 0 18px',
  },
  footer: {
    fontSize: '12px',
    color: brand.muted,
    lineHeight: '1.5',
    margin: '0',
  },
  signature: {
    fontFamily: brand.displayFont,
    fontSize: '13px',
    color: brand.ink,
    letterSpacing: '0.06em',
    textTransform: 'uppercase' as const,
    margin: '6px 0 0',
    fontWeight: 700 as const,
  },
}
