INSERT INTO public.jobs (name) VALUES
('1208 1st Ave'),
('2117 Sadler Ave'),
('3720 Benham Ave'),
('7055 Polk Lane'),
('Arcadia Lot # 10'),
('Bonterra Lot # 102'),
('Bonterra Lot # 112'),
('Bonterra Lot # 113'),
('Bonterra Lot # 114'),
('Bonterra Lot # 124'),
('Bonterra Lot # 127'),
('Bonterra Lot # 132'),
('Bonterra Lot # 134'),
('Bonterra Lot # 137'),
('CIA Pay App'),
('Echo Lot # 5'),
('Hamilton Development'),
('Hamilton Lot # 10'),
('Hamilton Lot # 12'),
('Hamilton Lot # 13'),
('Hamilton Lot # 14'),
('Hamilton Lot # 15'),
('Hamilton Lot # 17'),
('Hamilton Lot # 18'),
('Hamilton Lot # 20'),
('Hamilton Lot # 22'),
('Hamilton Lot # 23'),
('Hamilton Lot # 24'),
('Hamilton Lot # 31'),
('Hamilton Lot # 34'),
('Hamilton Lot # 36'),
('Hamilton Lot # 37'),
('Hamilton Lot # 38'),
('Hillside Ave Haul off'),
('LPC Cross Dock'),
('Polk Lane'),
('Primm Farms Lot # 7'),
('Primm Farms Lot # 18'),
('Trinity # 003'),
('Twin Springs')
ON CONFLICT DO NOTHING;